// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ASTNode is the predicate function for astnode builders.
type ASTNode func(*sql.Selector)

// CallRelationship is the predicate function for callrelationship builders.
type CallRelationship func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// ImportStatement is the predicate function for importstatement builders.
type ImportStatement func(*sql.Selector)

// InheritanceRelationship is the predicate function for inheritancerelationship builders.
type InheritanceRelationship func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Symbol is the predicate function for symbol builders.
type Symbol func(*sql.Selector)

// SymbolReference is the predicate function for symbolreference builders.
type SymbolReference func(*sql.Selector)
