# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

issues:
  # Exclude fixture directories from linting (test data files)
  exclude-dirs:
    - plugin/callgraph/fixtures
    - lang/fixtures
