package depsusage

// pythonModuleDistributions maps a top level import name to the distribution
// that installs it, when the two names differ. Names that differ only in
// case, "-", "_" or "." are not here: a consumer compares them after
// normalization (PEP 503).
var pythonModuleDistributions = map[string]string{
	"Bio":                "biopython",
	"Crypto":             "pycryptodome",
	"Cryptodome":         "pycryptodomex",
	"MySQLdb":            "mysqlclient",
	"OpenGL":             "pyopengl",
	"OpenSSL":            "pyopenssl",
	"PIL":                "pillow",
	"Xlib":               "python-xlib",
	"agents":             "openai-agents",
	"apiclient":          "google-api-python-client",
	"attr":               "attrs",
	"bs4":                "beautifulsoup4",
	"bson":               "pymongo",
	"cairo":              "pycairo",
	"consul":             "python-consul",
	"cv2":                "opencv-python",
	"dateutil":           "python-dateutil",
	"discord":            "discord.py",
	"dns":                "dnspython",
	"docx":               "python-docx",
	"dotenv":             "python-dotenv",
	"faiss":              "faiss-cpu",
	"fitz":               "pymupdf",
	"gi":                 "pygobject",
	"git":                "gitpython",
	"github":             "pygithub",
	"gitlab":             "python-gitlab",
	"google.protobuf":    "protobuf",
	"googleapiclient":    "google-api-python-client",
	"grpc":               "grpcio",
	"grpc_tools":         "grpcio-tools",
	"jenkins":            "python-jenkins",
	"jose":               "python-jose",
	"jwt":                "pyjwt",
	"kafka":              "kafka-python",
	"ldap":               "python-ldap",
	"magic":              "python-magic",
	"memcache":           "python-memcached",
	"mpl_toolkits":       "matplotlib",
	"multipart":          "python-multipart",
	"nacl":               "pynacl",
	"pkg_resources":      "setuptools",
	"pptx":               "python-pptx",
	"pythoncom":          "pywin32",
	"ruamel.yaml":        "ruamel.yaml",
	"serial":             "pyserial",
	"serpapi":            "google-search-results",
	"skimage":            "scikit-image",
	"sklearn":            "scikit-learn",
	"slugify":            "python-slugify",
	"snappy":             "python-snappy",
	"socks":              "pysocks",
	"speech_recognition": "speechrecognition",
	"telegram":           "python-telegram-bot",
	"umap":               "umap-learn",
	"usb":                "pyusb",
	"vertexai":           "google-cloud-aiplatform",
	"websocket":          "websocket-client",
	"win32api":           "pywin32",
	"win32con":           "pywin32",
	"yaml":               "pyyaml",
	"zmq":                "pyzmq",
}
