// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/code/examples/astdb/ent/callrelationship"
	"github.com/safedep/code/examples/astdb/ent/file"
	"github.com/safedep/code/examples/astdb/ent/predicate"
	"github.com/safedep/code/examples/astdb/ent/symbol"
)

// CallRelationshipQuery is the builder for querying CallRelationship entities.
type CallRelationshipQuery struct {
	config
	ctx              *QueryContext
	order            []callrelationship.OrderOption
	inters           []Interceptor
	predicates       []predicate.CallRelationship
	withCaller       *SymbolQuery
	withCallee       *SymbolQuery
	withCallSiteFile *FileQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CallRelationshipQuery builder.
func (_q *CallRelationshipQuery) Where(ps ...predicate.CallRelationship) *CallRelationshipQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CallRelationshipQuery) Limit(limit int) *CallRelationshipQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CallRelationshipQuery) Offset(offset int) *CallRelationshipQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CallRelationshipQuery) Unique(unique bool) *CallRelationshipQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CallRelationshipQuery) Order(o ...callrelationship.OrderOption) *CallRelationshipQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCaller chains the current query on the "caller" edge.
func (_q *CallRelationshipQuery) QueryCaller() *SymbolQuery {
	query := (&SymbolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(callrelationship.Table, callrelationship.FieldID, selector),
			sqlgraph.To(symbol.Table, symbol.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, callrelationship.CallerTable, callrelationship.CallerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCallee chains the current query on the "callee" edge.
func (_q *CallRelationshipQuery) QueryCallee() *SymbolQuery {
	query := (&SymbolClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(callrelationship.Table, callrelationship.FieldID, selector),
			sqlgraph.To(symbol.Table, symbol.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, callrelationship.CalleeTable, callrelationship.CalleeColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCallSiteFile chains the current query on the "call_site_file" edge.
func (_q *CallRelationshipQuery) QueryCallSiteFile() *FileQuery {
	query := (&FileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(callrelationship.Table, callrelationship.FieldID, selector),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, callrelationship.CallSiteFileTable, callrelationship.CallSiteFileColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CallRelationship entity from the query.
// Returns a *NotFoundError when no CallRelationship was found.
func (_q *CallRelationshipQuery) First(ctx context.Context) (*CallRelationship, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{callrelationship.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CallRelationshipQuery) FirstX(ctx context.Context) *CallRelationship {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CallRelationship ID from the query.
// Returns a *NotFoundError when no CallRelationship ID was found.
func (_q *CallRelationshipQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{callrelationship.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CallRelationshipQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CallRelationship entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CallRelationship entity is found.
// Returns a *NotFoundError when no CallRelationship entities are found.
func (_q *CallRelationshipQuery) Only(ctx context.Context) (*CallRelationship, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{callrelationship.Label}
	default:
		return nil, &NotSingularError{callrelationship.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CallRelationshipQuery) OnlyX(ctx context.Context) *CallRelationship {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CallRelationship ID in the query.
// Returns a *NotSingularError when more than one CallRelationship ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CallRelationshipQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{callrelationship.Label}
	default:
		err = &NotSingularError{callrelationship.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CallRelationshipQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CallRelationships.
func (_q *CallRelationshipQuery) All(ctx context.Context) ([]*CallRelationship, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CallRelationship, *CallRelationshipQuery]()
	return withInterceptors[[]*CallRelationship](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CallRelationshipQuery) AllX(ctx context.Context) []*CallRelationship {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CallRelationship IDs.
func (_q *CallRelationshipQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(callrelationship.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CallRelationshipQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CallRelationshipQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CallRelationshipQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CallRelationshipQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CallRelationshipQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CallRelationshipQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CallRelationshipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CallRelationshipQuery) Clone() *CallRelationshipQuery {
	if _q == nil {
		return nil
	}
	return &CallRelationshipQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]callrelationship.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.CallRelationship{}, _q.predicates...),
		withCaller:       _q.withCaller.Clone(),
		withCallee:       _q.withCallee.Clone(),
		withCallSiteFile: _q.withCallSiteFile.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCaller tells the query-builder to eager-load the nodes that are connected to
// the "caller" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallRelationshipQuery) WithCaller(opts ...func(*SymbolQuery)) *CallRelationshipQuery {
	query := (&SymbolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCaller = query
	return _q
}

// WithCallee tells the query-builder to eager-load the nodes that are connected to
// the "callee" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallRelationshipQuery) WithCallee(opts ...func(*SymbolQuery)) *CallRelationshipQuery {
	query := (&SymbolClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCallee = query
	return _q
}

// WithCallSiteFile tells the query-builder to eager-load the nodes that are connected to
// the "call_site_file" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CallRelationshipQuery) WithCallSiteFile(opts ...func(*FileQuery)) *CallRelationshipQuery {
	query := (&FileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCallSiteFile = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CallSiteLine int `json:"call_site_line,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CallRelationship.Query().
//		GroupBy(callrelationship.FieldCallSiteLine).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CallRelationshipQuery) GroupBy(field string, fields ...string) *CallRelationshipGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CallRelationshipGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = callrelationship.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CallSiteLine int `json:"call_site_line,omitempty"`
//	}
//
//	client.CallRelationship.Query().
//		Select(callrelationship.FieldCallSiteLine).
//		Scan(ctx, &v)
func (_q *CallRelationshipQuery) Select(fields ...string) *CallRelationshipSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CallRelationshipSelect{CallRelationshipQuery: _q}
	sbuild.label = callrelationship.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CallRelationshipSelect configured with the given aggregations.
func (_q *CallRelationshipQuery) Aggregate(fns ...AggregateFunc) *CallRelationshipSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CallRelationshipQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !callrelationship.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CallRelationshipQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CallRelationship, error) {
	var (
		nodes       = []*CallRelationship{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withCaller != nil,
			_q.withCallee != nil,
			_q.withCallSiteFile != nil,
		}
	)
	if _q.withCaller != nil || _q.withCallee != nil || _q.withCallSiteFile != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, callrelationship.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CallRelationship).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CallRelationship{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCaller; query != nil {
		if err := _q.loadCaller(ctx, query, nodes, nil,
			func(n *CallRelationship, e *Symbol) { n.Edges.Caller = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCallee; query != nil {
		if err := _q.loadCallee(ctx, query, nodes, nil,
			func(n *CallRelationship, e *Symbol) { n.Edges.Callee = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCallSiteFile; query != nil {
		if err := _q.loadCallSiteFile(ctx, query, nodes, nil,
			func(n *CallRelationship, e *File) { n.Edges.CallSiteFile = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CallRelationshipQuery) loadCaller(ctx context.Context, query *SymbolQuery, nodes []*CallRelationship, init func(*CallRelationship), assign func(*CallRelationship, *Symbol)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CallRelationship)
	for i := range nodes {
		if nodes[i].caller_id == nil {
			continue
		}
		fk := *nodes[i].caller_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(symbol.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "caller_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CallRelationshipQuery) loadCallee(ctx context.Context, query *SymbolQuery, nodes []*CallRelationship, init func(*CallRelationship), assign func(*CallRelationship, *Symbol)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CallRelationship)
	for i := range nodes {
		if nodes[i].callee_id == nil {
			continue
		}
		fk := *nodes[i].callee_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(symbol.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "callee_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CallRelationshipQuery) loadCallSiteFile(ctx context.Context, query *FileQuery, nodes []*CallRelationship, init func(*CallRelationship), assign func(*CallRelationship, *File)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CallRelationship)
	for i := range nodes {
		if nodes[i].call_site_file_id == nil {
			continue
		}
		fk := *nodes[i].call_site_file_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(file.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "call_site_file_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CallRelationshipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CallRelationshipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(callrelationship.Table, callrelationship.Columns, sqlgraph.NewFieldSpec(callrelationship.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, callrelationship.FieldID)
		for i := range fields {
			if fields[i] != callrelationship.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CallRelationshipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(callrelationship.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = callrelationship.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CallRelationshipGroupBy is the group-by builder for CallRelationship entities.
type CallRelationshipGroupBy struct {
	selector
	build *CallRelationshipQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CallRelationshipGroupBy) Aggregate(fns ...AggregateFunc) *CallRelationshipGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CallRelationshipGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CallRelationshipQuery, *CallRelationshipGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CallRelationshipGroupBy) sqlScan(ctx context.Context, root *CallRelationshipQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CallRelationshipSelect is the builder for selecting fields of CallRelationship entities.
type CallRelationshipSelect struct {
	*CallRelationshipQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CallRelationshipSelect) Aggregate(fns ...AggregateFunc) *CallRelationshipSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CallRelationshipSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CallRelationshipQuery, *CallRelationshipSelect](ctx, _s.CallRelationshipQuery, _s, _s.inters, v)
}

func (_s *CallRelationshipSelect) sqlScan(ctx context.Context, root *CallRelationshipQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
