// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/safedep/code/ent/callgraphnode"
	"github.com/safedep/code/ent/predicate"
)

// CallgraphNodeDelete is the builder for deleting a CallgraphNode entity.
type CallgraphNodeDelete struct {
	config
	hooks    []Hook
	mutation *CallgraphNodeMutation
}

// Where appends a list predicates to the CallgraphNodeDelete builder.
func (cnd *CallgraphNodeDelete) Where(ps ...predicate.CallgraphNode) *CallgraphNodeDelete {
	cnd.mutation.Where(ps...)
	return cnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cnd *CallgraphNodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cnd.sqlExec, cnd.mutation, cnd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cnd *CallgraphNodeDelete) ExecX(ctx context.Context) int {
	n, err := cnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cnd *CallgraphNodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(callgraphnode.Table, sqlgraph.NewFieldSpec(callgraphnode.FieldID, field.TypeInt))
	if ps := cnd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cnd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cnd.mutation.done = true
	return affected, err
}

// CallgraphNodeDeleteOne is the builder for deleting a single CallgraphNode entity.
type CallgraphNodeDeleteOne struct {
	cnd *CallgraphNodeDelete
}

// Where appends a list predicates to the CallgraphNodeDelete builder.
func (cndo *CallgraphNodeDeleteOne) Where(ps ...predicate.CallgraphNode) *CallgraphNodeDeleteOne {
	cndo.cnd.mutation.Where(ps...)
	return cndo
}

// Exec executes the deletion query.
func (cndo *CallgraphNodeDeleteOne) Exec(ctx context.Context) error {
	n, err := cndo.cnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{callgraphnode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cndo *CallgraphNodeDeleteOne) ExecX(ctx context.Context) {
	if err := cndo.Exec(ctx); err != nil {
		panic(err)
	}
}
