#!/bin/bash

# Generate a list of Go standard library packages
OUTPUT_FILE="$(dirname "$0")/../pkg/helpers/go_stdlibs.go"

echo "Generating Go standard library package list to: $OUTPUT_FILE"

# Create Go file with package list
cat > "$OUTPUT_FILE" << EOL
// Code generated by scripts/generate_go_stdlibs.sh; DO NOT EDIT.
package helpers

// GoStdLibPkgs is a map of all Go standard library packages
var GoStdLibs = map[string]bool{
EOL

# Run go list std and append each package to the map
go list std | while read -r pkg; do
    echo "    \"$pkg\": true," >> "$OUTPUT_FILE"
done

# Close the map declaration
echo "}" >> "$OUTPUT_FILE"

echo "Go standard library package list generated successfully"